version: 2.1
orbs:
  # use Cypress orb from CircleCI registry
  cypress: cypress-io/cypress@1.11.0

executors:
  mac:
    macos:
      xcode: "10.1.0"

jobs:
  release:
    executor: cypress/base-10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - run: npm cypress run --record --key 00c14645-d80d-4747-a200-6ce8f94b3cb9