version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 4
          group: 4 machines
          command: npx cypress run --record --key ff8e402a-5212-42be-a79e-38aef6ff8ced --parallel